In [1]:
import numpy as np
from numpy import linalg as LA

In [12]:
def Kronecker_product(a):
    if len(a) == 2:
        return np.kron(a[0],a[1])
    else:
        return np.kron(a[0], Kronecker_product(a[1:]))
    
def JW_transform(j, length):
    sigma = np.array([[0, 1], [0, 0]])
    sigma_z = np.array([[1, 0], [0, -1]])
    I = np.eye(2)
    operators = []
    for k in range(j):
        operators.append(sigma_z)
    operators.append(sigma)
    for k in range(length-j-1):
        operators.append(I)
    return -Kronecker_product(operators)

length = 2
c = []
for i in range(length):
    c.append(JW_transform(i, length))

def a(c,i):
    return c[i] + c[i].T

def b(c,i):
    return -1j*(c[i].T-c[i])
    
print(c)
print(a(c,0))
print(b(c,0))

[array([[-0., -0., -1., -0.],
       [-0., -0., -0., -1.],
       [-0., -0., -0., -0.],
       [-0., -0., -0., -0.]]), array([[ 0, -1,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  1],
       [ 0,  0,  0,  0]])]
[[-0. -0. -1. -0.]
 [-0. -0. -0. -1.]
 [-1. -0. -0. -0.]
 [-0. -1. -0. -0.]]
[[0.-0.j 0.-0.j 0.-1.j 0.-0.j]
 [0.-0.j 0.-0.j 0.-0.j 0.-1.j]
 [0.+1.j 0.-0.j 0.-0.j 0.-0.j]
 [0.-0.j 0.+1.j 0.-0.j 0.-0.j]]


In [9]:
#Hamiltonian, for simplicity J,h = 1

def Dirac(c):
    H = 0
    for i in range(length - 1):
        H += -c[i].T.dot(c[i+1]) + c[i].dot(c[i+1].T)
        H -= (c[i].T.dot(c[i+1].T) - c[i].dot(c[i+1]))
    for i in range(length):
        H -= np.eye(2**length)-2*(c[i].T.dot(c[i])) + c[i].dot(c[i].T)
        v,w = np.linalg.eig(H)
    return H,v,w

def Majorana(c):
    H = 0
    for i in range(length - 1):
        H -= 1j*b(c,i).dot(a(c,i+1))
    for i in range(length):
        H -= 1j*a(c,i).dot(b(c,i))
        v,w = np.linalg.eig(H)
    return H,v,w

print(Majorana(c))

(array([[-2.+0.j,  0.+0.j,  0.+0.j, -1.+0.j],
       [ 0.+0.j,  0.+0.j, -1.+0.j,  0.+0.j],
       [ 0.+0.j, -1.+0.j,  0.+0.j,  0.+0.j],
       [-1.+0.j,  0.+0.j,  0.+0.j,  2.+0.j]]), array([-2.23606798+0.j,  2.23606798+0.j,  1.        +0.j, -1.        +0.j]), array([[ 0.97324899+0.j, -0.22975292+0.j,  0.        +0.j,
         0.        +0.j],
       [-0.        +0.j,  0.        +0.j,  0.70710678+0.j,
         0.70710678+0.j],
       [-0.        +0.j,  0.        +0.j, -0.70710678+0.j,
         0.70710678+0.j],
       [ 0.22975292-0.j,  0.97324899+0.j,  0.        +0.j,
         0.        +0.j]]))
